# Generated by Django 4.1 on 2023-08-18 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок страницы"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Краткое описание"
                    ),
                ),
                ("url", models.URLField(verbose_name="Ссылка на страницу")),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("book", "Book"),
                            ("article", "Article"),
                            ("music", "Music"),
                            ("video", "Video"),
                        ],
                        default="website",
                        max_length=7,
                        verbose_name="Тип ссылки",
                    ),
                ),
                (
                    "og_image",
                    models.URLField(
                        blank=True, null=True, verbose_name="Картинка превью"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время изменения"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
